### ISSUE TITLE
Doesn't work over VNC

### ISSUE THREAD

**Issue by SigvaldS42** [Gordon999/Pi_LIbCamera_GUI#11]
Sorry, but
 File "/home/dsl/PiLibCameraGUI.py", line 310, in <module>
    windowSurfaceObj = pygame.display.set_mode((preview_width + (bw*2),dis_height),  0, 24)
pygame.error: No available displays

Itried it over VNC, because i don't have any Monitor at my Pi4
SigvaldS

**Comment by Gordon999** [comment]
Sorry, l have never used VNC so l don't know if it will work or not.

This may help. https://raspberrypi.stackexchange.com/questions/9776/how-to-run-pygame-window-on-vnc-remote-desktop

**Comment by SigvaldS42** [comment]
Thank you for your answer. But that don't solve the problem.

**Comment by Gordon999** [comment]
Closed
