### ISSUE TITLE
NameError: name 'max_gain' is not defined

### ISSUE THREAD

**Issue by neolu** [Gordon999/Pi_LIbCamera_GUI#12]
Still capture image received
Traceback (most recent call last):
  File "/home/dev/works/Pi_LIbCamera_GUI/PiLibCameraGUI.py", line 253, in <module>
    still_limits[8] = max_gain
NameError: name 'max_gain' is not defined

**Comment by Gordon999** [comment]
Which version code ? Eg v4.32
Which camera are you using ?
What is displaying on the window top bar eg Pi v1 camera?
What dimensions is the image in test.jpg image it saved ?

Sounds like it isn't detecting a valid image size for a camera.

**Comment by Gordon999** [comment]
I have uploaded v4.35 which should solve the issue.
When run it will print the size of the test.jpg image.
Let me know if it shows 'Unknown Camera' in the title bar and if so let me know the camera you are using
