### ISSUE TITLE
Photos and videos not saving.

### ISSUE THREAD

**Issue by Acidforbreakfast** [Gordon999/Pi_LIbCamera_GUI#13]
After installing this GUI, photos and videos are no longer saving using the libcamera commands in Terminal. Apologies if I am not posting this 'issue' correctly, this is the first time I have posted anything to GitHub. Any help in removing this GUI from my machine would be appreciated. Thank you for all your work!

**Comment by Gordon999** [comment]
I assume this is after you have exited the script ? Are you using the EXIT button to EXIT?

Failure to use the EXIT will leave the subprocess running occupying the camera.

What terminal command are you using ?

Do you get any errors reported ?

Does it work after a reboot?

**Comment by Acidforbreakfast** [comment]
Yes previously I had used the EXIT button to exit. I just ran your script again specifically to exit using the EXIT button, and now running `libcamera-jpeg -o testpostexit.jpg` is working as expected. I will have a bit more of a tinker, but as for now this seems to have resolved the issue.

Thank you again for your work.

**Comment by Gordon999** [comment]
Thanks
