### ISSUE TITLE
multiple cameras on arducam multiplexor 

### ISSUE THREAD

**Issue by iisideeffektii** [Gordon999/Pi_LIbCamera_GUI#16]
When calling libcamera apps there is an --camera option to select which camera is being used.  I have lots --camera 0 and --camera 1.  Is ther a way to switch cameras using this method?

**Comment by Gordon999** [comment]
I'll take a look at adding the option

**Comment by Gordon999** [comment]
Try the latest version. Switch camera by right clicking on preview image

**Comment by Gordon999** [comment]
It would be good to know if this worked OK.

**Comment by iisideeffektii** [comment]
Camera switching now works.  I have an imx477 and an arducam 64mp camera both switching between the two. I am able to switch between the two by right clicking the preview window.   

There is now one issue with the arducam 64mp camera, autofocus no longer works.

ERROR: *** option '--autofocus' is ambiguous and matches '--autofocus-mode', '--autofocus-range', '--autofocus-speed', and '--autofocus-window' ***

**Comment by jvoss11** [comment]
what multiplexer are you using?

**Comment by iisideeffektii** [comment]
Arducam multicamera adaptor module v2.2

**Comment by jvoss11** [comment]
wow in the documentation for that multiplexer is said it has to be the same cameras.  No mixing of different CMOS cameras.

**Comment by iisideeffektii** [comment]
Yeah, that was my concern when I started my multicam project after reading the documentation, but I have had no issues using these two cameras.  From command line I haven't had any problems with the cameras using the most current libcamera-apps and a 4gb pi 4b.

**Comment by jvoss11** [comment]
Nice..  so you still on bullseye or did you up grade to bookworm

**Comment by iisideeffektii** [comment]
Bullseye, I didn't even know there was a new version of the os.  I will probably wait for a while and stick with Bullseye for now on my project

**Comment by Gordon999** [comment]
The AF issue on the 64MP is probably due to the libcamera version. Are you using the Arducam version ? I think you need to.

https://docs.arducam.com/Raspberry-Pi-Camera/Native-camera/Quick-Start-Guide/

You could try the PiLibCamera_GUI_Ard version. It uses the existing pi libcamera-apps BUT only has manual focus and a simple AF when you click to auto focus or zoom.

**Comment by Gordon999** [comment]
Assumed fixed
