### ISSUE TITLE
possibilities of streaming or brodcasting video

### ISSUE THREAD

**Issue by jvoss11** [Gordon999/Pi_LIbCamera_GUI#17]
This is more of a question then an issue.

Can you broadcast the video live from your program?  if not is this something you might consider?

**Comment by Gordon999** [comment]
I don't think so as it uses libcamera-vid -segment to grab frames, but l may take a look at it.

**Comment by Gordon999** [comment]
TCP Video streaming added, right click on Capture Video. Default port is 5000.
Will run for the Video length set.
Note no preview of the video.

To view try vlc tcp/h264://ip-addr-of-server:port eg vlc tcp/h264://192.168.1.89:5000

**Comment by Gordon999** [comment]
Assumed solved
