### ISSUE TITLE
Issue and a request

### ISSUE THREAD

**Issue by astrome2050** [Gordon999/Pi_LIbCamera_GUI#2]
First off great GUI! It is easier to take photos without the command lines. 

I have an issue and a request. 
I am using the 64mp camera and the gui on boot does recognize the 64mp camera. 
fresh stock raspberry pi os 64 bit.
I have not made any alterations to the OS nor to your code in this instance.

Issue. 
Whenever I zoom in and take the photo while zoomed in, it gives me this error and stops responding entirely.

Line 1687 - zxo = ((igw-zws[(4-zoom) + ((Pi_Cam-1)* 4)])/2)/igw
IndexError: list index out of range

Request. 
I noticed "Line 90 - max_ar = 10 # ???" 
I don't specifics about that line but I did look up the official max exposure setting for the 64mp ardu cam and it's 435 seconds. 

"# whatever value set it MUST be in shutters list !!" 
On a different card I did add 435 to the shutter list and timed it but it didn't work, even added steps up to 435 and still didn't work.

https://www.arducam.com/64mp-ultra-high-res-camera-raspberry-pi/

Thanks.

**Comment by Gordon999** [comment]
Just spotted this issue. I'll take a look at the issues. I don't have a 64mp camera, just the 16mp, for testing.

**Comment by Gordon999** [comment]
Hopefully fixed

**Comment by Gordon999** [comment]
Hopefully fixed
