### ISSUE TITLE
Error - Pi_Cam is not defined

### ISSUE THREAD

**Issue by pssikand** [Gordon999/Pi_LIbCamera_GUI#7]
Hi,
Thanks for your work on this tool.
I am new to this "world" of Pi, Arducam, etc.
I just got my Pi4B up an running, and installed the Arducam 64 MP camera, release earlier this year.

After running the "beta" auto install, I ran the python script as indicated, but an error appeared.
In reviewing the output on the screen, my camera indicated a 4624x3472 image size, which did not meet any of the selections in the script on lines 196-210, so the variable Pi_Cam was not assigned a value which caused an error on line 214.

I am not sure if this is particular to my setup specifically, or if the default resolution on the camera is as I indicated above.

I made a small edit to the script, and assigned the Pi_Cam value 5 for the 4624 igw, and it seems to have fired up just fine.

Thought you might want the feedback.

**Comment by Vados1er** [comment]
I've got the same issue 
Changing to 4624 don't allow to take picture at full res for the 64mp 
Any idea to resolve that ?

**Comment by Gordon999** [comment]
Unfortunately I don't have a 64mp camera to test but assume it has worked for others in the past.
If you run **libcamera-jpeg -n -t 1000 -e jpg -o test64mp.jpg** what size image do you get ?
It should produce a full res image which for the 64mp should be 9152 x 6944.

**Comment by Gordon999** [comment]
I have updated with a temporary fix, to recognise 4624, whilst I look for the cause.

**Comment by pssikand** [comment]
The issue that the 64 MP camera on a Pi4B (4GB RAM)  is unable to gracefully handle 9152x resolution is being discussed in various threads elsewhere.  It seems to be related to buffer allocation, and even with the CMA specified at 512M, there is not enough space to capture a full res image with preview.

My comment initially reported is that the logic in this script leaves an error because it is looking for a specific image size.  My simple fix was to change the line from " == 9152" to " <= 9152" as a stop gap measure.

With respect to the command 
libcamera-jpeg -n -t 1000 -e jpg -o test64mp.jpg
results in a 4624x3472 image.  It seems that this is a default, and you may have to specify higher res if you want that.

So far, outside of this script, the only successful combination I have found is below, given the cma=512M in cmdline.txt (or cma-512 in the config.txt), it results in full res image.
libcamera-still --autofocus --timestamp --width 9152 --height 6944 --nopreview

It seems the preview takes up RAM, and eliminating it allows enough space.

Elsewhere, I have found comments about a memory leak, such that only a few images are captured successfully, before failure to allocate a buffer occurs, but I have not tested this issue yet.

Interestingly, the Arducam website seems to distinguish resolution for a Pi vs "Camera Module" ... albeit, for "Video Mode", but I assume it extends to Still mode as well ?  The forum at Arducam seems to distinguish camera capability vs. Pi integration, and there is some blame shifting that the Camera works fine, and the Pi is having memory issues.
https://www.arducam.com/64mp-ultra-high-res-camera-raspberry-pi/

It is not clear whether there is any difference in resolution capability using Pi4B vs. CM4 (Compute module) ?  If that is even a possibility.

**Comment by Gordon999** [comment]
OK. I can accommodate that in the still taking section.
The video /timelapse section is already limited in the script to lower than 9152 due to the buffer limit.

**Comment by Gordon999** [comment]
Please try v3.9

**Comment by Vados1er** [comment]
Thank it work

**Comment by Gordon999** [comment]
I am pleased it worked. I am still a bit confused how it apparently used to work, based on the the version evanhelene used. Maybe something changed in the Arducam code ?

**Comment by Gordon999** [comment]
Closed

**Comment by pssikand** [comment]
Thank you, this seems to work.
