### ISSUE TITLE
Programm failed to take a picture with shutter speed more than 1s

### ISSUE THREAD

**Issue by Vados1er** [Gordon999/Pi_LIbCamera_GUI#8]
Arducam 64mp
Raspi 4 8g
Bullseye
Libcamera gui 3.9

When i put more than 1s in shuter speed the programm crash

Will it Be possible to desactivate the preview before shooting? Therefor it will free the memory ?

Thanks

**Comment by Gordon999** [comment]
If between 1 and 19 seconds it uses --timelapse. It does stop the preview by stopping the subprocess.
In line 1854 change the sizes to -width 4624 -height 3472 and see if that works.
Sounds like a buffer issue.

**Comment by Gordon999** [comment]
I have uploaded a beta version with a different timelapse technique between 1 and 19 seconds, pleases try it.

**Comment by Gordon999** [comment]
Hopefully fixed in v3.91.

**Comment by Vados1er** [comment]
Hi
Great update 
But when i take still image with shutter up to 15s the image os save at lower résolution 16mp instead of 64mp
Perhaps a consequence of Raspberry pi Cma ?

By the way great job
Thank's

**Comment by Gordon999** [comment]
This is normal, it was added for astro use. Above 10 seconds it will happen. Do you want it removed or possibly added as an option?

if Pi_Cam == 5 and sspeed > 10000000 and mode == 0:
                                 rpistr += " --width 4624 --height 3472 " # > 10 seconds use 16MP superpixel mode for higher light sensitivity
                        elif Pi_Cam == 5:
                                rpistr += " --width 9152 --height 6944"

**Comment by Vados1er** [comment]
Do you mean it's like binding pixel ?
If so as an option for Astro photo it will be Nice to have binding x2, x3 ans x4
I plan to do some Astrophotography test Whith the 64mp cam and your software
Thanks

**Comment by Gordon999** [comment]
Yes the 64mp does 2x2 binning in superpixel mode. I'll add it as an option.

**Comment by Gordon999** [comment]
Uploaded v4.00. Click on right of capture still or timelapse button for 2x2 binning. Will only show and work if using arducam 64mp camera in manual mode

**Comment by Gordon999** [comment]
assume fixed
