### ISSUE TITLE
How to start in full screen "mode"?

### ISSUE THREAD

**Issue by SunboX** [Gordon999/Pi_LIbCamera_GUI#9]
Hi,

first, thanks a lot for this great tool!

Is there any way to start the app in "full screen mode" so that it takes the whole screen? Would be also nice to get rid of the title/status bar at all.

greetings and thanks,
André

**Comment by Gordon999** [comment]
FULLSCREEN option added

set to 1 for FULLSCREEN

preview_width  = 800
preview_height = 600
fullscreen     = 1 # set to 1 for FULLSCREEN

you may have to experiment with preview_width and preview_height to suit screen

**Comment by Gordon999** [comment]
Completed
